# Generated by Django 4.1.7 on 2023-04-27 14:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author_set",
                to="app_book.authormodel",
            ),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_set",
                to="app_book.bookcategorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_set",
                to="app_book.storemodel",
            ),
        ),
        migrations.AlterField(
            model_name="storemodel",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
