# Generated by Django 4.1.7 on 2023-03-25 12:05

import app_book.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app_book.manager.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_verified',
        ),
    ]
