# Generated by Django 4.1.7 on 2023-05-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0002_alter_bookmodel_author_alter_bookmodel_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=525, null=True)),
                ("content", models.TextField(blank=True, max_length=1525, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="authormodel",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.AlterModelOptions(
            name="bookcategorymodel",
            options={
                "ordering": ["-id"],
                "verbose_name": "Book Category",
                "verbose_name_plural": "Book Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="bookmodel",
            options={"verbose_name": "Book", "verbose_name_plural": "Books"},
        ),
        migrations.AlterModelOptions(
            name="contactmodel",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="ordermodel",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="publishermodel",
            options={"verbose_name": "Publisher", "verbose_name_plural": "Publishers"},
        ),
        migrations.AlterModelOptions(
            name="reviewmodel",
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews"},
        ),
    ]
