# Generated by Django 4.1.7 on 2023-04-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_book",
            "0004_authormodel_bookcategorymodel_bookmodel_contactmodel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_book.bookcategorymodel",
            ),
        ),
    ]
