# Generated by Django 4.1.7 on 2023-04-23 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0005_bookmodel_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authormodel",
            old_name="name",
            new_name="author_name",
        ),
    ]
