# Generated by Django 4.1.7 on 2023-05-17 15:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0005_alter_reviewmodel_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storemodel",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="BD", unique=True
            ),
        ),
    ]
