# Generated by Django 4.1.7 on 2023-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0006_rename_name_authormodel_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="description",
            field=models.TextField(blank=True, max_length=925, null=True),
        ),
    ]
