# Generated by Django 4.2.7 on 2023-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0007_alter_ordermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
