# Generated by Django 4.1.7 on 2023-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0007_alter_bookmodel_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmodel",
            name="sub_title",
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
