# Generated by Django 4.2.7 on 2023-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0008_ordermodel_billing_address_ordermodel_billing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='books_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
