# Generated by Django 4.1.7 on 2023-04-25 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0008_remove_bookmodel_sub_title_bookmodel_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storemodel",
            options={"verbose_name": "Store", "verbose_name_plural": "Stores"},
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storemodel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
