# Generated by Django 4.2.7 on 2023-12-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0009_ordermodel_books_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodel',
            options={'ordering': ['-id'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='publishermodel',
            options={'ordering': ['-id'], 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='storemodel',
            options={'ordering': ['-id'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
