# Generated by Django 4.1.7 on 2023-12-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_book", "0010_alter_authormodel_options_alter_bookmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_set",
                to="app_book.authormodel",
            ),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_set",
                to="app_book.bookcategorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_set",
                to="app_book.storemodel",
            ),
        ),
    ]
