# Generated by Django 4.2.7 on 2023-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0011_alter_bookmodel_author_alter_bookmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Visa Card', 'Visa Card'), ('Master Card', 'Master Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad')], default='Credit Card', max_length=100, null=True),
        ),
    ]
